name: Deployment Pipeline

on:
  push:
    branches:
      - main

jobs:
  simple_deployment_pipeline:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: "20"
      - name: Install dependencies
        run: npm install
      - name: Check style
        run: npm run eslint
      - name: Fix Lint Errors
        run: npm run eslint -- --fix
      - name: Run Build
        run: npm run build
      - name: Run Jest Test
        run: npm test
      - name: Install Playwright dependencies
        run: npm ci
      - name: Install Playwright Browsers
        run: npx playwright install --with-deps
      - name: Run Playwright tests
        run: npm run test:e2e
      - uses: actions/upload-artifact@v4
        if: ${{ !cancelled() }}
        with:
          name: playwright-report
          path: playwright-report/
          retention-days: 30
      - name: Cypress e2e tests
        uses: cypress-io/github-action@v5
        with:
          start: npm run start-prod
          wait-on: http://localhost:5000
          command: npx cypress run --headless
      - name: Trigger deployment
        run: curl https://api.render.com/deploy/${{ secrets.RENDER_SERVICE_ID }}?key=${{ secrets.RENDER_API_KEY }}
